2020-05-09 22:55:41,771 ERROR: Exception on /index [GET] [in c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask_login\utils.py", line 271, in decorated_view
    return current_app.login_manager.unauthorized()
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask_login\login_manager.py", line 165, in unauthorized
    flash(self.login_message, category=self.login_message_category)
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\helpers.py", line 423, in flash
    session["_flashes"] = flashes
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\werkzeug\local.py", line 350, in __setitem__
    self._get_current_object()[key] = value
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\sessions.py", line 103, in _fail
    "The session is unavailable because no secret "
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2020-05-09 22:55:41,771 ERROR: Exception on /index [GET] [in c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask_login\utils.py", line 271, in decorated_view
    return current_app.login_manager.unauthorized()
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask_login\login_manager.py", line 165, in unauthorized
    flash(self.login_message, category=self.login_message_category)
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\helpers.py", line 423, in flash
    session["_flashes"] = flashes
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\werkzeug\local.py", line 350, in __setitem__
    self._get_current_object()[key] = value
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\sessions.py", line 103, in _fail
    "The session is unavailable because no secret "
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
